### PR TITLE
Add interactiveModeTimeout and MFAPasswordMaxDays as optional variables

### PR DESCRIPTION
**Pull request by deepbluemussel**
I usually set default vars in default/main.yml but here I kept the structure of the j2 template with default variables inside.

### CODE REVIEW

**Comment by adamsbytes** [comment]
Thanks for this PR! Happy to incorporate this into the role. I've re-targeted the PR against a dev branch so that the latest OVHBastion release can be targeted as well.

**Review by adamsbytes — APPROVED** [review]
Looks good!

**Comment by deepbluemussel** [comment]
You're welcome, thanks for the role.
I would have liked to be able to create groups/users/server access with ansible too but it might be too time consuming  : b

**Comment by adamsbytes** [comment]
I am planning on creating a utility just like that, once I'm finished I'll let you know!

**Comment by deepbluemussel** [comment]
Sounds great!
I wonder if OVH have such a tool already. Would be nice if it is a native ovhbastion functionality.

**Pull request merged**
